--- # Serial execution example
- hosts: all
#  This will result in installing elinks one host at first time and the 2 host at second time and then 3 host at 3rd time (batch by batch)
  serial
  - 1
  - 2
  - 3
  become: yes
  tasks: 
    - name: Install elinks
      package:
        name: elinks
        state: latest
